[31m[1mERROR   [0m django.request:log.py:248 Internal Server Error: /getReturns
Traceback (most recent call last):
  File "C:\Emanuel\Universidad\Semestre7\PruebasDeSoftware\caso-3\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Emanuel\Universidad\Semestre7\PruebasDeSoftware\caso-3\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Emanuel\Universidad\Semestre7\PruebasDeSoftware\caso-3\env\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Emanuel\Universidad\Semestre7\PruebasDeSoftware\caso-3\financialSearch\views.py", line 46, in getReturns
    start = datetime.strptime(from_date, '%Y-%m-%d')
  File "C:\Users\emanu\AppData\Local\Programs\Python\Python313\Lib\_strptime.py", line 676, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emanu\AppData\Local\Programs\Python\Python313\Lib\_strptime.py", line 455, in _strptime
    raise ValueError("time data %r does not match format %r" %
                     (data_string, format))
ValueError: time data 'invalid-date' does not match format '%Y-%m-%d'